const fs = require('fs-extra');
const path = require('path');
const YAML = require('yaml');

const {
  meta,
  foundationColors,
  typography: typographyConfig,
  spacing: spacingConfig,
  rounded: roundedConfig,
  derivedComponents,
  derivedComponentGroups,
  derivedComponentShapes,
  extraComponents,
  proseTables,
} = require('../../design-md/designMdConfig.js');

const PACKAGE_ROOT = path.resolve(__dirname, '../..');
const REPO_ROOT = path.resolve(PACKAGE_ROOT, '../..');

const TOKENS_PATH = path.join(PACKAGE_ROOT, 'build/json/design-md.json');
const PROSE_PATH = path.join(PACKAGE_ROOT, 'design-md/prose.md');
const OUTPUT_PATH = path.join(REPO_ROOT, 'DESIGN.md');

/**
 * Deliberately timestamp-free, unlike `utils/createFileHeader`. DESIGN.md is
 * committed and checked for drift in CI, so a timestamp would make every build
 * report a change.
 */
const GENERATED_NOTICE = [
  '<!--',
  '  Do not edit this file directly.',
  '',
  '  The YAML front matter is generated from the design tokens in',
  '  packages/design-tokens/tokens/ (curated by design-md/designMdConfig.js).',
  '  The prose below is authored in packages/design-tokens/design-md/prose.md.',
  '',
  '  Regenerate with `pnpm build-tokens`.',
  '-->',
].join('\n');

/** DESIGN.md section headings, in the order the spec requires. */
const CANONICAL_SECTIONS = [
  ['Overview', 'Brand & Style'],
  ['Colors'],
  ['Typography'],
  ['Layout', 'Layout & Spacing'],
  ['Elevation & Depth', 'Elevation'],
  ['Shapes'],
  ['Components'],
  ["Do's and Don'ts"],
];

/** Groups the token JSON exposes as `<group>.<key>`. */
const COLOR_GROUPS = ['background', 'font', 'border'];

/** Which component sub-token each color group maps onto. */
const COLOR_GROUP_TO_PROPERTY = {
  background: 'backgroundColor',
  font: 'textColor',
  border: 'borderColor',
};

/**
 * Resolve a dotted path (`color.background.primary`) to its token node.
 * Returns undefined rather than throwing so callers can decide.
 */
function lookup(tokens, dottedPath) {
  return dottedPath
    .split('.')
    .reduce((node, key) => (node == null ? undefined : node[key]), tokens);
}

/**
 * The token source carries a stray trailing semicolon on the `body` and `brand`
 * font families (see tokens/assets/fontFamily.json). Strip it here rather than
 * editing the token, which would also change the generated CSS.
 */
function sanitizeFontFamily(value) {
  return String(value).replace(/;\s*$/, '').trim();
}

/**
 * DESIGN.md Dimensions must carry a px/em/rem suffix. Hyphen's scales are
 * already transformed to rem by the design.md platform, so this mostly guards
 * against values that slipped through untransformed.
 */
function toDimension(value) {
  const raw = String(value).trim();
  if (/^-?\d*\.?\d+(px|em|rem)$/.test(raw)) return raw;
  if (/^-?\d*\.?\d+$/.test(raw)) return `${raw}rem`;
  return undefined;
}

/** A unitless multiplier (line-height) or a Dimension. */
function toLineHeight(value) {
  const raw = String(value).trim();
  if (/^-?\d*\.?\d+$/.test(raw)) return Number(raw);
  return toDimension(raw);
}

/**
 * DESIGN.md's Color type covers CSS color strings. Hyphen's `brand-gradient*`
 * tokens are `linear-gradient(...)` values, which are images rather than
 * colors — they must not be published as color tokens.
 */
function isColor(value) {
  if (typeof value !== 'string') return false;
  const raw = value.trim();
  if (raw === '') return false;
  if (/gradient\s*\(/i.test(raw)) return false;
  return (
    raw === 'transparent' ||
    /^#[0-9a-f]{3,8}$/i.test(raw) ||
    /^(rgb|rgba|hsl|hsla|hwb|oklch|oklab|lch|lab|color-mix)\s*\(/i.test(raw) ||
    /^[a-z]+$/i.test(raw)
  );
}

/**
 * Builds the `colors` map.
 *
 * Two ways in:
 *
 * - `define` always publishes the requested name. Foundation roles use this,
 *   because they are the stable vocabulary the prose and the hand-written
 *   components refer to — they must not be renamed by deduplication.
 * - `intern` deduplicates by the (light, dark) pair, so a derived component
 *   color that already exists under a foundation name reuses that name instead
 *   of adding a redundant token. This is what collapses, for example,
 *   `button-primary`'s background into `{colors.primary}`.
 *
 * Both return `{ ref, darkRef }` rather than a bare name, so callers always
 * reference the token that actually got published.
 */
function createColorTable() {
  /** name -> value */
  const colors = {};
  /** "light|dark" -> { name, darkName } */
  const byValue = new Map();

  const key = (light, dark) => `${light}|${dark ?? ''}`;

  function publish(name, light, dark) {
    const hasDark = isColor(dark) && dark !== light;
    colors[name] = light;
    const darkName = hasDark ? `${name}-dark` : undefined;
    if (darkName) colors[darkName] = dark;

    const entry = { name, darkName };
    const valueKey = key(light, hasDark ? dark : undefined);
    if (!byValue.has(valueKey)) byValue.set(valueKey, entry);
    return entry;
  }

  const toRefs = (entry) => ({
    ref: `{colors.${entry.name}}`,
    darkRef: entry.darkName ? `{colors.${entry.darkName}}` : undefined,
  });

  return {
    colors,

    define(name, light, dark) {
      if (!isColor(light)) return undefined;
      return toRefs(publish(name, light, dark));
    },

    intern(name, light, dark) {
      if (!isColor(light)) return undefined;
      const hasDark = isColor(dark) && dark !== light;
      const existing = byValue.get(key(light, hasDark ? dark : undefined));
      return toRefs(existing ?? publish(name, light, dark));
    },
  };
}

/** Compose the `typography` map from Hyphen's separate scales. */
function buildTypography(tokens) {
  const typography = {};
  for (const [name, level] of Object.entries(typographyConfig)) {
    const family = lookup(tokens, level.fontFamily);
    const size = lookup(tokens, level.fontSize);
    const weight = lookup(tokens, level.fontWeight);
    const height = lookup(tokens, level.lineHeight);
    if (!family || !size || !weight || !height) {
      throw new Error(`Typography level "${name}" references a token that does not exist.`);
    }
    typography[name] = {
      fontFamily: sanitizeFontFamily(family.value),
      fontSize: toDimension(size.value),
      fontWeight: Number(weight.value),
      lineHeight: toLineHeight(height.value),
    };
  }
  return typography;
}

/** Emit a Dimension scale (`spacing`, `rounded`) from a token group. */
function buildScale(tokens, { group, omit = [] }) {
  const node = lookup(tokens, group);
  if (!node) throw new Error(`Token group "${group}" does not exist.`);
  const scale = {};
  for (const [name, token] of Object.entries(node)) {
    if (omit.includes(name)) continue;
    const dimension = toDimension(token.value);
    if (dimension !== undefined) scale[name] = dimension;
  }
  return scale;
}

/** Longest prefix of `name` present in `table`, or undefined. */
function longestPrefixMatch(table, name) {
  const prefix = Object.keys(table)
    .filter((candidate) => name === candidate || name.startsWith(`${candidate}-`))
    .sort((a, b) => b.length - a.length)[0];
  return prefix === undefined ? undefined : table[prefix];
}

/** Static properties merged onto a derived component. */
function shapeFor(name) {
  return longestPrefixMatch(derivedComponentShapes, name) ?? {};
}

/** Which color groups a derived component draws from. */
function groupsFor(name) {
  return longestPrefixMatch(derivedComponentGroups, name) ?? COLOR_GROUPS;
}

/**
 * Build the `components` map.
 *
 * Derived entries come from the intersection of Hyphen's background / font /
 * border tokens for a given semantic key. Any entry with a dark value also gets
 * a `<name>-dark` sibling, which is what keeps the spec's `orphaned-tokens`
 * rule quiet: every `-dark` color token is referenced by a `-dark` component.
 */
function buildComponents(tokens, intern) {
  const components = {};

  for (const name of derivedComponents) {
    const light = {};
    const dark = {};

    for (const group of groupsFor(name)) {
      const token = lookup(tokens, `color.${group}.${name}`);
      if (!token) continue;
      const property = COLOR_GROUP_TO_PROPERTY[group];
      const color = intern(`${name}-${group}`, token.value, token.darkValue);
      if (!color) continue;
      light[property] = color.ref;
      if (color.darkRef) dark[property] = color.darkRef;
    }

    if (Object.keys(light).length === 0) continue;
    components[name] = { ...light, ...shapeFor(name) };
    if (Object.keys(dark).length > 0) components[`${name}-dark`] = dark;
  }

  // Checkbox splits across two token names, so it does not fit the derived shape.
  const checkboxChecked = lookup(tokens, 'color.background.checkbox-checked');
  const checkboxBorder = lookup(tokens, 'color.border.checkbox');
  if (checkboxChecked && checkboxBorder) {
    const border = intern('checkbox-border', checkboxBorder.value, checkboxBorder.darkValue);
    const checked = intern(
      'checkbox-checked-background',
      checkboxChecked.value,
      checkboxChecked.darkValue
    );
    components.checkbox = { borderColor: border.ref, rounded: '{rounded.xs}' };
    components['checkbox-checked'] = { backgroundColor: checked.ref, rounded: '{rounded.xs}' };
    if (border.darkRef) components['checkbox-dark'] = { borderColor: border.darkRef };
    if (checked.darkRef) {
      components['checkbox-checked-dark'] = { backgroundColor: checked.darkRef };
    }
  }

  return { ...components, ...extraComponents };
}

/**
 * Give every component a `-dark` sibling when any color it references has a
 * dark value.
 *
 * Derived components already produce theirs while interning; this covers the
 * hand-written entries in `extraComponents`, and is what keeps the spec's
 * `orphaned-tokens` rule satisfied — a published `-dark` color is only
 * meaningful if some component actually uses it.
 */
function withDarkVariants(components, colors) {
  const result = {};

  for (const [name, component] of Object.entries(components)) {
    result[name] = component;
    if (name.endsWith('-dark') || components[`${name}-dark`]) continue;

    const dark = {};
    for (const [property, value] of Object.entries(component)) {
      if (typeof value !== 'string') continue;
      const match = value.match(/^\{colors\.(.+)\}$/);
      if (match && colors[`${match[1]}-dark`] !== undefined) {
        dark[property] = `{colors.${match[1]}-dark}`;
      }
    }
    if (Object.keys(dark).length > 0) result[`${name}-dark`] = dark;
  }

  return result;
}

/** Render a token group as a markdown table for the prose body. */
function renderProseTable(tokens, { group, title }) {
  const node = lookup(tokens, group);
  if (!node) return '';
  const rows = Object.entries(node)
    .map(([name, token]) => `| \`${name}\` | \`${token.value}\` |`)
    .join('\n');
  return `**${title}**\n\n| Token | Value |\n| --- | --- |\n${rows}`;
}

/**
 * Validate the hand-authored prose. Duplicate `##` headings are a hard error in
 * the DESIGN.md spec, and sections must appear in canonical order.
 */
function validateProse(prose) {
  const headings = [...prose.matchAll(/^##\s+(.+?)\s*$/gm)].map((match) => match[1]);

  const seen = new Set();
  for (const heading of headings) {
    if (seen.has(heading)) {
      throw new Error(
        `prose.md has a duplicate "## ${heading}" heading. The DESIGN.md spec rejects files with duplicate sections.`
      );
    }
    seen.add(heading);
  }

  let cursor = -1;
  for (const heading of headings) {
    const index = CANONICAL_SECTIONS.findIndex((aliases) => aliases.includes(heading));
    if (index === -1) continue; // Unknown sections are preserved by the spec.
    if (index <= cursor) {
      throw new Error(
        `prose.md has "## ${heading}" out of order. Canonical order is: ${CANONICAL_SECTIONS.map(
          ([canonical]) => canonical
        ).join(', ')}.`
      );
    }
    cursor = index;
  }

  return headings;
}

/** Assemble the full DESIGN.md contents. */
function buildDesignMd(tokens, prose) {
  const { colors, define, intern } = createColorTable();

  for (const [name, tokenPath] of Object.entries(foundationColors)) {
    const token = lookup(tokens, tokenPath);
    if (!token) throw new Error(`Foundation color "${name}" points at missing token "${tokenPath}".`);
    define(name, token.value, token.darkValue);
  }

  const components = withDarkVariants(buildComponents(tokens, intern), colors);

  const frontMatter = {
    version: meta.version,
    name: meta.name,
    description: meta.description,
    colors,
    typography: buildTypography(tokens),
    rounded: buildScale(tokens, roundedConfig),
    spacing: buildScale(tokens, spacingConfig),
    components,
  };

  assertReferencesResolve(frontMatter);

  const body = prose.replace(/\{\{\s*table:(\w+)\s*\}\}/g, (match, name) => {
    const table = proseTables[name];
    if (!table) throw new Error(`prose.md references unknown table "${name}".`);
    return renderProseTable(tokens, table);
  });

  // `yaml` rather than `js-yaml`: it double-quotes strings the way the spec's
  // own examples do, and it is the parser the official linter uses, so what is
  // written here round-trips exactly.
  const yamlText = YAML.stringify(frontMatter, {
    lineWidth: 0,
    defaultStringType: 'QUOTE_DOUBLE',
    defaultKeyType: 'PLAIN',
  });

  return `---\n${yamlText}---\n\n${GENERATED_NOTICE}\n\n${body.trim()}\n`;
}

/**
 * Every `{group.token}` reference must resolve. Broken references are the only
 * error-severity finding in the DESIGN.md linter, so catch them here where the
 * message can name the component.
 */
function assertReferencesResolve(frontMatter) {
  const problems = [];
  for (const [componentName, component] of Object.entries(frontMatter.components)) {
    for (const [property, value] of Object.entries(component)) {
      if (typeof value !== 'string') continue;
      const match = value.match(/^\{(.+)\}$/);
      if (!match) continue;
      if (lookup(frontMatter, match[1]) === undefined) {
        problems.push(`components.${componentName}.${property} -> ${value}`);
      }
    }
  }
  if (problems.length > 0) {
    throw new Error(`DESIGN.md has unresolved token references:\n  ${problems.join('\n  ')}`);
  }
}

/**
 * Generate DESIGN.md at the repo root.
 *
 * @param {{ check?: boolean }} options - in `check` mode nothing is written;
 *   the return value reports whether the committed file is up to date.
 * @returns {{ changed: boolean, content: string, outputPath: string }}
 */
function generateDesignMd({ check = false } = {}) {
  if (!fs.existsSync(TOKENS_PATH)) {
    throw new Error(
      `${TOKENS_PATH} does not exist. Run \`pnpm build-tokens\` before generating DESIGN.md.`
    );
  }

  const tokens = fs.readJsonSync(TOKENS_PATH);
  const prose = fs.readFileSync(PROSE_PATH, 'utf8');
  validateProse(prose);

  const content = buildDesignMd(tokens, prose);
  const existing = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : null;
  const changed = existing !== content;

  if (!check && changed) {
    fs.outputFileSync(OUTPUT_PATH, content);
  }

  return { changed, content, outputPath: OUTPUT_PATH };
}

module.exports = generateDesignMd;
module.exports.default = generateDesignMd;
module.exports.lookup = lookup;
module.exports.sanitizeFontFamily = sanitizeFontFamily;
module.exports.toDimension = toDimension;
module.exports.toLineHeight = toLineHeight;
module.exports.isColor = isColor;
module.exports.createColorTable = createColorTable;
module.exports.validateProse = validateProse;
module.exports.buildDesignMd = buildDesignMd;
module.exports.assertReferencesResolve = assertReferencesResolve;
