name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: test
        run: pnpm test

      - name: build
        run: pnpm build

      - name: Publish
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            npm publish --ignore-scripts --tag beta --access public
          else
            npm publish --ignore-scripts --access public
          fi
